/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STD_TYPES.h"
#include "GPIO_interface.h"


/*RCC Implementing: to enable the CLK for the GPIO Driver*/
#define AHB1_BASE			(0x40020000)
#define RCC_OFFSET			(0x3800u)
#define RCC_BASE			(AHB1_BASE + RCC_OFFSET)
#define RCC_AHB1ENR_OFFSET	(0x30u)
#define RCC_AHB1ENR			*((volatile u32 *)(RCC_BASE + RCC_AHB1ENR_OFFSET))




int main(void)
{

	/*Enabling the CLK of the GPIOA Preph*/
	RCC_AHB1ENR |= (1u << 0);

	/*DIO_voidPinSetAltFn(GPIOA_PORT, PIN7, AF7);
	DIO_voidPinSetAltFn(GPIOA_PORT, PIN8, AF8);

	DIO_voidSetOutSpeed(GPIOA_PORT, PIN4, OUTPUT_MEDUIM_SPEED);*/

	/*configuring the pin*/
	DIO_voidSetPinMode(GPIOA_PORT, PIN5, MODE_OUTPUT);

	DIO_voidSetPinMode(GPIOA_PORT, PIN0, MODE_INPUT);

	DIO_voidSetPull(GPIOA_PORT, PIN0, PULL_UP);

	DIO_voidWriteDataOdr(GPIOA_PORT, PIN5, LOW);

	u8 Local_u8InputVal = 1;

	while(1)
	{
		/*DIO_voidWriteDataOdr(GPIOA_PORT, PIN5, HIGH);
		for (int i = 0; i < 100000; i++) {};
		DIO_voidWriteDataOdr(GPIOA_PORT, PIN5, LOW);
		for (int i = 0; i < 100000; i++) {};*/

		/*Delay for denouncing*/
		for (int i = 0; i < 10000; i++) {};

		/*This to read the data from the pin0 at PORTA*/
		Local_u8InputVal = DIO_u8ReadData(GPIOA_PORT, PIN0);

		/*Turning on the led if the button is pressed*/
		if (Local_u8InputVal == 0)
		{
			DIO_voidWriteDataOdr(GPIOA_PORT, PIN5, HIGH);
		}

		else
		{
			DIO_voidWriteDataOdr(GPIOA_PORT, PIN5, LOW);
		}
	}

}
